"""Email attachment parsing and response attachment loading."""

import base64
import logging
import os
import tempfile
from pathlib import Path
from typing import Any, Optional

from fastapi import HTTPException

from automail.db.pocketbase.client import _get_binary, _list_all
from automail.pipeline.intent.consumers import attachment_intent_names

try:
    from docling.document_converter import DocumentConverter  # pyright: ignore[reportMissingImports]
except ModuleNotFoundError:  # pragma: no cover - exercised in production images without attachments extra
    DocumentConverter = None

logger = logging.getLogger(__name__)

# Singleton: Docling initialisation loads ML models — create once on first use.
_doc_converter = None


def _get_doc_converter() -> Any:
    global _doc_converter

    if _doc_converter is not None:
        return _doc_converter

    if DocumentConverter is None:
        return None

    _doc_converter = DocumentConverter()
    return _doc_converter


def parse_email_attachments(email: Any) -> dict[str, str]:
    """
    Parse email attachments using Docling and extract text content.

    Args:
        email: Email object with attachments list (filename, base64)

    Returns:
        Dictionary mapping filename to extracted text content
    """
    if not hasattr(email, "attachments") or not email.attachments:
        return {}

    converter = _get_doc_converter()
    if converter is None:
        logger.warning("Docling is not installed; attachment text extraction is disabled")
        return {
            attachment.filename: "[Attachment text extraction unavailable on this deployment]"
            for attachment in email.attachments
        }

    parsed_attachments: dict[str, str] = {}

    for attachment in email.attachments:
        temp_file_path = None
        try:
            file_bytes = base64.b64decode(attachment.base64)

            suffix = Path(attachment.filename).suffix or ".tmp"
            with tempfile.NamedTemporaryFile(suffix=suffix, delete=False) as temp_file:
                temp_file.write(file_bytes)
                temp_file_path = temp_file.name

            result = converter.convert(temp_file_path)
            text_content = result.document.export_to_markdown()
            parsed_attachments[attachment.filename] = text_content

            logger.info(
                "Successfully parsed attachment: %s (%d chars)",
                attachment.filename,
                len(text_content),
            )

        except Exception as exc:
            logger.error("Failed to parse attachment %s: %s", attachment.filename, exc)
            parsed_attachments[attachment.filename] = f"[Unable to parse: {exc}]"

        finally:
            if temp_file_path and os.path.exists(temp_file_path):
                try:
                    os.unlink(temp_file_path)
                except Exception as exc:
                    logger.debug("Failed to clean up temp file %s: %s", temp_file_path, exc)

    return parsed_attachments


def _escape_pb(value: str) -> str:
    return value.replace("'", "\\'")


def _stored_pb_filename(record: dict) -> str:
    stored = record.get("file")
    if isinstance(stored, list):
        return str(stored[0]) if stored else ""
    return str(stored or "")


def load_attachment_files(
    agent_response: Any,
    intents_dir: Any = None,
    *,
    intent_result: Any = None,
    strict_intent_ownership: bool = False,
) -> Optional[list[dict[str, Any]]]:
    """
    Load attachment files from filenames and convert to base64.

    Search order:
    1. Attachments generated by HTTP tools during this run
    2. PocketBase-backed intent attachments
    """
    if not agent_response.response_attachments:
        return None

    attachments = []
    generated_by_name = {
        item.filename: item
        for item in getattr(agent_response, "generated_attachments", []) or []
    }
    project_id = getattr(intents_dir, "project_id", None)

    seen_filenames = set()
    for filename in agent_response.response_attachments:
        if filename in seen_filenames:
            continue
        seen_filenames.add(filename)

        try:
            if os.path.sep in filename or ".." in filename:
                raise HTTPException(
                    status_code=400,
                    detail=f"Invalid attachment filename: {filename} (path traversal not allowed)",
                )

            generated = generated_by_name.get(filename)
            if generated:
                attachments.append({
                    "filename": generated.filename,
                    "content_base64": generated.content_base64,
                    "content_type": generated.content_type or "application/octet-stream",
                    "size": generated.size or 0,
                    "source_tool": generated.source_tool,
                })
                continue

            if project_id:
                try:
                    filters = [
                        f"project='{_escape_pb(project_id)}'",
                        f"filename='{_escape_pb(filename)}'",
                    ]
                    preferred = []
                    intent_names = attachment_intent_names(
                        intent_result,
                        filename,
                        owners_only=strict_intent_ownership,
                    )
                    activated_intent = str(getattr(agent_response, "activated_intent", None) or "").strip()
                    if (
                        not strict_intent_ownership
                        and activated_intent
                        and activated_intent not in intent_names
                    ):
                        intent_names.append(activated_intent)
                    for intent_name in intent_names:
                        preferred = _list_all(
                            "intent_attachments",
                            " && ".join([*filters, f"intent='{_escape_pb(intent_name)}'"]),
                            per_page=1,
                        )
                        if preferred:
                            break
                    records = preferred
                    if not records and not strict_intent_ownership:
                        records = _list_all(
                            "intent_attachments",
                            " && ".join(filters),
                            per_page=1,
                        )
                    if records:
                        record = records[0]
                        stored_name = _stored_pb_filename(record)
                        if stored_name:
                            content, content_type = _get_binary(
                                f"/api/files/intent_attachments/{record['id']}/{stored_name}",
                            )
                            attachments.append({
                                "filename": filename,
                                "content_base64": base64.b64encode(content).decode("utf-8"),
                                "content_type": record.get("content_type")
                                or content_type
                                or "application/octet-stream",
                                "size": len(content),
                            })
                            continue
                except Exception:
                    logger.warning(
                        "Failed to load PocketBase intent attachment %s",
                        filename,
                        exc_info=True,
                    )

            raise FileNotFoundError(
                f"Attachment file '{filename}' not found in generated attachments or "
                "PocketBase intent attachments.",
            )

        except Exception as exc:
            raise HTTPException(
                status_code=500,
                detail=f"Error loading attachment {filename}: {exc}",
            )

    return attachments
