"""One message-level reply composer for all routed runbook concerns."""

from __future__ import annotations

import logging
from typing import Any

from langchain.agents import create_agent
from langchain.agents.structured_output import ToolStrategy

from automail.integrations.http_tool import current_generated_attachments
from automail.llm.usage import llm_stage
from automail.models import AgentResponse, Email, IdentityResult, IntentResult, ResponseDraft
from automail.pipeline.intent.helpers import _invoke_agent, _load_intent_feedback_learnings
from automail.pipeline.intent.intents_factory import (
    get_intent_response_attachments,
    get_known_intent_names,
)
from automail.pipeline.response.agent import _validate_response
from automail.pipeline.response.prompt_factory import (
    create_response_system_prompt,
    create_response_user_prompt,
)
from automail.support.pending_action_claims import (
    PENDING_ACTION_CLAIM_REASON_CODE,
    PendingActionClaimCheck,
    check_pending_action_claims,
)
from automail.support.safety_guidance import (
    SAFETY_GUIDANCE_MISSING_REASON_CODE,
    assess_lithium_battery_safety,
    missing_lithium_battery_safety_guidance,
)

logger = logging.getLogger(__name__)


def _matched_runbook_names(intent_result: IntentResult) -> list[str]:
    names: list[str] = []
    for concern in intent_result.concerns:
        name = str(concern.intent_name or "").strip()
        if concern.matched and name and name not in names:
            names.append(name)
    if not names and intent_result.matched and intent_result.intent_name:
        names.append(intent_result.intent_name)
    return names


def _available_attachments(
    intent_result: IntentResult,
    *,
    intents_dir: Any,
) -> tuple[list[dict[str, Any]], list[str]]:
    available: list[dict[str, Any]] = []
    always: list[str] = []
    seen: set[str] = set()
    for concern in intent_result.concerns:
        for attachment in concern.attachments:
            filename = str(attachment.filename or "").strip()
            if not filename or filename in seen:
                continue
            seen.add(filename)
            available.append({
                "filename": filename,
                "description": str(attachment.description or ""),
                "mode": str(attachment.mode or "dynamic"),
            })
            if str(attachment.mode or "").strip() in {"always", "generated"}:
                always.append(filename)
    if not available:
        for runbook_name in _matched_runbook_names(intent_result):
            for item in get_intent_response_attachments(runbook_name, intents_dir=intents_dir):
                filename = str(item.get("filename") or "").strip()
                if not filename or filename in seen:
                    continue
                seen.add(filename)
                available.append(item)
                if str(item.get("mode") or "").strip() == "always":
                    always.append(filename)
    for item in current_generated_attachments():
        filename = str(item.get("filename") or "").strip()
        if not filename or filename in seen:
            continue
        seen.add(filename)
        available.append(
            {
                "filename": filename,
                "description": str(item.get("description") or "Generated by a runbook tool"),
                "mode": "dynamic",
            }
        )
        if item.get("attach_to_response", True):
            always.append(filename)
    return available, always


def _reply_requires_human(intent_result: IntentResult) -> tuple[bool, str]:
    reasons: list[str] = []
    for concern in intent_result.concerns:
        if not concern.matched:
            reasons.append(concern.requires_human_reason or concern.error or "A concern has no matching runbook.")
        elif concern.requires_human or concern.status in {"requires_human", "failed"}:
            reasons.append(concern.requires_human_reason or concern.error or f"{concern.intent_name} requires review.")
    clean_reasons = list(dict.fromkeys(reason.strip() for reason in reasons if reason and reason.strip()))
    return bool(clean_reasons), " ".join(clean_reasons)[:1_000]


def _draft_review_requirements(
    intent_result: IntentResult,
    draft: ResponseDraft,
) -> tuple[bool, str]:
    requires_human, outcome_reason = _reply_requires_human(intent_result)
    reasons = [outcome_reason] if outcome_reason else []
    expected_ids = [concern.concern_id for concern in intent_result.concerns]
    if expected_ids:
        covered_ids = [item.strip() for item in draft.covered_concern_ids if item.strip()]
        if len(covered_ids) != len(expected_ids) or set(covered_ids) != set(expected_ids):
            requires_human = True
            reasons.append("Reply composer did not confirm exact coverage of every concern.")
    expected_obligation_ids = [
        obligation.obligation_id
        for concern in intent_result.concerns
        for obligation in concern.answer_obligations
        if obligation.obligation_id
    ]
    if expected_obligation_ids:
        covered_obligation_ids = [
            item.strip() for item in draft.covered_obligation_ids if item.strip()
        ]
        if (
            len(covered_obligation_ids) != len(expected_obligation_ids)
            or set(covered_obligation_ids) != set(expected_obligation_ids)
        ):
            requires_human = True
            reasons.append("Reply composer did not confirm exact coverage of every answer obligation.")
    if draft.requires_human:
        requires_human = True
        reasons.append(draft.requires_human_reason or "Reply composer requested human review.")
    if draft.conflicting_requirements:
        requires_human = True
        reasons.append(
            "Conflicting runbook requirements: "
            + "; ".join(item.strip() for item in draft.conflicting_requirements if item.strip())
        )
    clean_reasons = list(dict.fromkeys(reason.strip() for reason in reasons if reason.strip()))
    return requires_human, " ".join(clean_reasons)[:1_000]


def _pending_action_claim_check(
    intent_result: IntentResult,
    answer: str,
) -> PendingActionClaimCheck:
    pending_actions = [
        {
            "name": action.name,
            "label": action.label,
            "status": "pending_approval",
        }
        for concern in intent_result.concerns
        for action in concern.action_outcomes
        if action.status in {"proposed", "pending_input"}
    ]
    tool_evidence = [
        {
            "name": evidence.tool_name,
            "method": evidence.method,
            "status": evidence.status,
            "facts": [fact.model_dump() for fact in evidence.facts],
        }
        for concern in intent_result.concerns
        for evidence in concern.tool_evidence
    ]
    return check_pending_action_claims(
        answer=answer,
        runbook_actions=pending_actions,
        tool_evidence=tool_evidence,
    )


def compose_pipeline_reply(
    *,
    email: Email,
    identity_result: IdentityResult | None,
    intent_result: IntentResult,
    intents_dir: Any = None,
    config_path: Any = None,
    creator: str | None = None,
    parsed_attachments: dict[str, str] | None = None,
    tenant_id: str | None = None,
    project_id: str | None = None,
) -> AgentResponse | None:
    """Draft one reply after every matched runbook has produced an outcome."""
    safety_assessment = assess_lithium_battery_safety(
        subject=email.subject,
        body=email.body,
    )
    runbook_names = _matched_runbook_names(intent_result)
    if not runbook_names:
        return None

    from automail.core.config import read_config
    from automail.llm import create_llm, resolve_effective_config

    config = resolve_effective_config(read_config(config_path=config_path), tenant_id, project_id)
    available_attachments, always_filenames = _available_attachments(
        intent_result,
        intents_dir=intents_dir,
    )
    learnings: list[str] = []
    for runbook_name in runbook_names:
        for learning in _load_intent_feedback_learnings(
            runbook_name,
            tenant_id,
            project_id=project_id,
            intents_dir=intents_dir,
            target="response",
        ):
            if learning not in learnings:
                learnings.append(learning)

    user_prompt = create_response_user_prompt(
        email,
        parsed_attachments,
        creator=creator,
        identity_result=identity_result,
        intent_result=intent_result,
        tenant_id=tenant_id,
        intents_dir=intents_dir,
        intent_learnings=learnings or None,
        available_response_attachments=available_attachments,
        company_name=config.org_name,
        company_description=config.org_description,
    )
    response_llm = create_llm(config, timeout=120, max_retries=3)
    usage_context = getattr(response_llm, "_mantly_usage_context", None)
    agent = create_agent(
        model=response_llm,
        tools=[],
        system_prompt=create_response_system_prompt(
            tenant_id=tenant_id,
            config_path=config_path,
            intents_dir=intents_dir,
        ),
        response_format=ToolStrategy(ResponseDraft),
    )
    with llm_stage("response"):
        result = _invoke_agent(
            agent,
            user_prompt,
            usage_context=usage_context,
            run_name="ticket_reply_composer",
            tags=["mantly", "response", "composer"],
            metadata={
                "tenant_id": tenant_id,
                "project_id": project_id,
                "runbook_names": runbook_names,
                "concern_count": len(intent_result.concerns) or 1,
                "source": "pipeline.response.composer",
            },
        )
    draft = result.get("structured_response") if isinstance(result, dict) else None
    if not isinstance(draft, ResponseDraft):
        raise ValueError("Ticket reply composer returned no structured response.")
    missing_safety = (
        missing_lithium_battery_safety_guidance(draft.response_text)
        if safety_assessment.active
        else ()
    )
    if missing_safety:
        raise ValueError(
            SAFETY_GUIDANCE_MISSING_REASON_CODE + ": " + ", ".join(missing_safety)
        )
    pending_action_check = _pending_action_claim_check(intent_result, draft.response_text)
    if pending_action_check.blocked:
        raise ValueError(PENDING_ACTION_CLAIM_REASON_CODE)

    requires_human, requires_human_reason = _draft_review_requirements(intent_result, draft)
    if safety_assessment.active:
        requires_human = True
        requires_human_reason = " ".join(
            dict.fromkeys(
                reason
                for reason in (
                    requires_human_reason,
                    safety_assessment.requires_human_reason,
                )
                if reason
            )
        )[:1_000]
    response = AgentResponse(
        response_text=draft.response_text,
        response_attachments=draft.response_attachments,
        response_cc=draft.response_cc,
        response_bcc=draft.response_bcc,
        activated_intent=intent_result.intent_name or runbook_names[0],
        requires_human=requires_human,
        requires_human_reason=requires_human_reason or None,
    )
    if always_filenames:
        merged = list(response.response_attachments or [])
        for filename in always_filenames:
            if filename not in merged:
                merged.append(filename)
        response.response_attachments = merged
    valid_attachment_filenames = {
        str(item.get("filename") or "").strip()
        for item in available_attachments
        if str(item.get("filename") or "").strip()
    }
    return _validate_response(
        response,
        get_known_intent_names(intents_dir=intents_dir),
        # Exact matched-runbook ownership was already resolved above. Avoid
        # project-wide filename validation, which can cross runbooks.
        intents_dir=None,
        extra_valid_attachment_filenames=valid_attachment_filenames,
    )
