#!/usr/bin/env python3
"""Compile all automail/*.py files to native .so extensions using Cython.

Usage (from the backend/ directory):
    python scripts/compile_sources.py

This script:
  1. Finds all .py files under automail/ (excluding __init__.py)
  2. Compiles each to a platform-native .so extension via Cython + GCC
  3. Removes the original .py source files
  4. Replaces each __init__.py with an empty stub (required for imports)

After compilation the automail/ package contains only .so files and
empty __init__.py stubs — no readable Python source remains.
"""

import glob
import os
import shutil
import subprocess
import sys


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(root)

    # Collect all .py files in automail/ (excluding __init__.py)
    py_files = sorted(glob.glob("automail/**/*.py", recursive=True))
    source_files = [f for f in py_files if not f.endswith("__init__.py")]
    init_files = [f for f in py_files if f.endswith("__init__.py")]

    if not source_files:
        print("No .py files found to compile.")
        sys.exit(1)

    print(f"Found {len(source_files)} files to compile, {len(init_files)} __init__.py stubs to keep")

    # Write a temporary setup.py for Cython
    setup_content = f"""\
import os
from setuptools import setup, Extension
from Cython.Build import cythonize

sources = {source_files!r}

extensions = []
for src in sources:
    # Convert file path to module name: automail/api/auth.py → automail.api.auth
    module_name = src.replace(os.sep, ".").replace("/", ".").removesuffix(".py")
    extensions.append(Extension(module_name, [src]))

setup(
    packages=[],
    ext_modules=cythonize(
        extensions,
        compiler_directives={{"language_level": 3}},
        nthreads=os.cpu_count() or 1,
    ),
)
"""
    setup_path = os.path.join(root, "_setup_compile.py")
    with open(setup_path, "w") as f:
        f.write(setup_content)

    # Run the compilation
    print("Compiling with Cython...")
    result = subprocess.run(
        [sys.executable, setup_path, "build_ext", "--inplace"],
        capture_output=False,
    )
    if result.returncode != 0:
        print("Compilation failed!")
        sys.exit(1)

    # Remove original .py source files
    print("Removing .py source files...")
    for f in source_files:
        os.remove(f)
        print(f"  removed {f}")

    # Replace __init__.py files with empty stubs
    print("Replacing __init__.py with empty stubs...")
    for f in init_files:
        with open(f, "w") as fh:
            fh.write("# compiled package\n")
        print(f"  stubbed {f}")

    # Clean up build artifacts
    for cleanup in ["_setup_compile.py", "build"]:
        path = os.path.join(root, cleanup)
        if os.path.isfile(path):
            os.remove(path)
        elif os.path.isdir(path):
            shutil.rmtree(path)

    # Also remove .c files generated by Cython
    for c_file in glob.glob("automail/**/*.c", recursive=True):
        os.remove(c_file)

    # Count compiled .so files
    so_files = glob.glob("automail/**/*.so", recursive=True)
    print(f"\nDone! Compiled {len(so_files)} .so extensions.")
    print("No .py source files remain in automail/.")


if __name__ == "__main__":
    main()
