"""Shared helpers for intent classification and processing."""

import logging
import re
from typing import Any

from langchain.messages import AIMessage
from tenacity import RetryCallState, retry, retry_if_exception_type, stop_after_attempt, wait_exponential

from automail.core.runtime_secrets import load_runtime_secrets
from automail.integrations.http_tool import _make_http_tool, current_generated_attachments, raw_tool_to_definition
from automail.models import Email, IdentityResult, IntentAction
from automail.pipeline.intent.intents_factory import (
    get_intent_frontmatters,
    get_intent_tools,
)

logger = logging.getLogger(__name__)


def _retry_exception(retry_state: RetryCallState) -> BaseException | str:
    outcome = retry_state.outcome
    if outcome is None:
        return ""
    exc = outcome.exception()
    return exc if exc is not None else ""


def _generated_attachment_prompt_items() -> list[dict]:
    """Return tool-generated attachments already available to response drafting."""
    items: list[dict] = []
    for attachment in current_generated_attachments():
        if not attachment.get("attach_to_response", True):
            continue
        filename = str(attachment.get("filename") or "").strip()
        if not filename:
            continue
        source_tool = str(attachment.get("source_tool") or "").strip()
        content_type = str(attachment.get("content_type") or "").strip()
        description_parts = []
        if source_tool:
            description_parts.append(f"generated by tool `{source_tool}`")
        if content_type:
            description_parts.append(content_type)
        items.append({
            "filename": filename,
            "description": ", ".join(description_parts),
            "mode": "generated",
        })
    return items


@retry(
    stop=stop_after_attempt(2),
    wait=wait_exponential(multiplier=2, min=2, max=10),
    retry=retry_if_exception_type(Exception),
    reraise=True,
    before_sleep=lambda rs: logger.warning(
        "Intent agent invoke failed (attempt %d), retrying: %s",
        rs.attempt_number, _retry_exception(rs),
    ),
)
def _invoke_agent(
    agent: Any,
    user_prompt: str,
    parsed_attachments: dict[str, str] | None = None,
    usage_context: dict[str, Any] | None = None,
    run_name: str | None = None,
    tags: list[str] | None = None,
    metadata: dict[str, Any] | None = None,
) -> dict[str, Any]:
    payload: dict[str, Any] = {"messages": [{"role": "user", "content": user_prompt}]}
    if parsed_attachments is not None:
        payload["parsed_attachments"] = parsed_attachments

    config: dict[str, Any] = {}
    if run_name:
        config["run_name"] = run_name
    if tags:
        config["tags"] = tags
    if metadata:
        config["metadata"] = metadata

    result = agent.invoke(payload, config=config) if config else agent.invoke(payload)
    from automail.llm.usage import record_usage_from_result

    record_usage_from_result(result, usage_context)
    return result


def _build_intents_list(intents_dir: Any = None) -> str:
    frontmatters = [
        fm for fm in get_intent_frontmatters(intents_dir=intents_dir)
        if fm.get("name") and fm.get("name") != "_else"
        and fm.get("active", True) is not False
        and str(fm.get("active", True)).lower() != "false"
    ]
    if not frontmatters:
        return "No intents available."
    lines = []
    for fm in frontmatters:
        name = fm.get("name", "unknown")
        description = fm.get("description", "No description")
        lines.append(f"**{name}**: {description}")
    return "\n".join(lines)


def _tool_calls_from_message(message: Any) -> list[dict[str, Any]]:
    if isinstance(message, AIMessage):
        return list(getattr(message, "tool_calls", []) or [])
    if isinstance(message, dict):
        return list(message.get("tool_calls") or [])
    return []


def _find_router_tool_call(messages: list[Any], tool_name: str) -> dict[str, Any] | None:
    """Find the first router tool call by name in LangChain result messages."""
    for message in messages:
        for tool_call in _tool_calls_from_message(message):
            if tool_call.get("name") == tool_name:
                args = tool_call.get("args")
                return args if isinstance(args, dict) else {}
    return None


def _find_activated_intent(messages: list[Any]) -> str | None:
    args = _find_router_tool_call(messages, "activate_intent")
    if args is None:
        return None
    intent_name = str(args.get("intent_name") or "").strip()
    return intent_name or None


def _find_no_match_reason(messages: list[Any]) -> str | None:
    args = _find_router_tool_call(messages, "no_match")
    if args is None:
        return None
    return str(args.get("reason") or "").strip()


def _build_intent_http_tools(
    intent_name: str,
    sender_email: str,
    intents_dir: Any = None,
    tenant_id: str | None = None,
    project_id: str | None = None,
    read_only_only: bool = False,
) -> list[Any]:
    """Load HTTP tool definitions from the intent's frontmatter and build LangChain tools."""
    raw_tools = get_intent_tools(intent_name, intents_dir=intents_dir)
    if not raw_tools:
        return []

    secrets = load_runtime_secrets(tenant_id, project_id)
    lc_tools: list[Any] = []
    for raw in raw_tools:
        if read_only_only and str(raw.get("method") or "").upper() != "GET":
            continue
        defn = raw_tool_to_definition(raw, secrets)
        if defn:
            lc_tools.append(_make_http_tool(defn, sender_email=sender_email))
    return lc_tools


def _load_intent_feedback_learnings(
    intent_name: str,
    tenant_id: str | None,
    project_id: str | None = None,
    intents_dir: Any = None,
    target: str | None = None,
) -> list[str]:
    """Load generated feedback learnings when enabled by intent and plan."""
    from automail.pipeline.intent.intents_factory import get_use_feedback_learnings

    if not get_use_feedback_learnings(intent_name, intents_dir=intents_dir):
        return []

    from automail.billing.plans import has_feature
    if not has_feature(tenant_id, "feedback_learnings"):
        return []

    from automail.db.pocketbase.client import get_intent_learnings
    return get_intent_learnings(
        intent_name,
        tenant_id=tenant_id,
        project_id=project_id,
        target=target,
    ) or []


def _append_feedback_learnings(system_prompt: str, learnings: list[str]) -> str:
    if not learnings:
        return system_prompt
    lines = "\n".join(f"{i}. {rule}" for i, rule in enumerate(learnings, 1))
    return (
        f"{system_prompt}\n\n"
        "## Feedback Learnings\n"
        "Apply these learned rules when processing this intent. They may affect "
        "customer context, action preparation, tool usage, workflow decisions, "
        "or generated attachment decisions.\n"
        f"{lines}"
    )


def _format_attachment_context(parsed_attachments: dict[str, str] | None = None, max_chars: int = 6000) -> str:
    """Format extracted attachment text for intent classification/processing."""
    if not parsed_attachments:
        return ""

    sections = []
    for filename, content in parsed_attachments.items():
        text = str(content or "")
        if len(text) > max_chars:
            text = f"{text[:max_chars]}\n\n[... truncated, {len(text) - max_chars} characters omitted ...]"
        sections.append(f"### {filename}\n\n{text}")
    return "\n\n".join(sections)


def _extract_mapping_placeholders(value: Any) -> set[str]:
    if isinstance(value, str):
        return set(re.findall(r"\{([^}]+)\}", value))
    if isinstance(value, dict):
        found: set[str] = set()
        for item in value.values():
            found.update(_extract_mapping_placeholders(item))
        return found
    if isinstance(value, list):
        found: set[str] = set()
        for item in value:
            found.update(_extract_mapping_placeholders(item))
        return found
    return set()


def _build_process_user_message(
    email: Email,
    identity_result: IdentityResult | None,
    actions: list[IntentAction],
    parsed_attachments: dict[str, str] | None = None,
) -> str:
    """Build the user message for the intent processing stage."""
    parts = [
        f"Subject: {email.subject}",
        f"From: {email.from_address}",
        "",
        email.body,
    ]

    attachment_context = _format_attachment_context(parsed_attachments)
    if attachment_context:
        parts.extend(["", "## Attachments", attachment_context])

    # Identity context
    if identity_result and identity_result.customer_found:
        parts.append("\n## Customer Identity")
        for key, value in identity_result.data.items():
            parts.append(f"- **{key}**: {value}")
    elif identity_result:
        parts.append("\n## Customer Identity\nNo customer record found.")

    # Fillable actions (tell the LLM what fields to extract)
    fillable = [a for a in actions if a.type in ("dropdown", "input", "calendar")]
    if fillable:
        parts.append("\n## Action Fields to Fill")
        parts.append(
            "Extract values from the email for these fields. "
            "Use the exact action name in your action_fills response. "
            "Leave initial_value as null if you cannot confidently infer a value.",
        )
        for a in fillable:
            desc = a.description or a.label or a.name
            extra = ""
            if a.type == "dropdown" and a.options:
                extra = f" (choose from: {', '.join(a.options)})"
            elif a.type == "calendar":
                extra = " (use ISO 8601 format: YYYY-MM-DD)"
            parts.append(f"- **{a.name}**: {desc}{extra}")

    button_actions = [a for a in actions if a.type == "button"]
    if button_actions:
        parts.append("\n## Action Buttons")
        parts.append(
            "These are fixed user-triggered actions. Use their descriptions as context "
            "when extracting values for related action fields. Do not return action_fills "
            "for button actions.",
        )
        for a in button_actions:
            desc = a.description or a.label or a.name
            mapped_fields = sorted(
                _extract_mapping_placeholders(a.query)
                | _extract_mapping_placeholders(a.body)
            )
            extra = f" (uses: {', '.join(mapped_fields)})" if mapped_fields else ""
            parts.append(f"- **{a.name}**: {desc}{extra}")

    return "\n".join(parts)
